# Generated by Django 3.0.2 on 2020-01-20 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200120_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_manager',
        ),
    ]
