# Generated by Django 3.0.2 on 2020-01-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_branch_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
