# Generated by Django 3.0.2 on 2020-01-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='transfered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
