# Generated by Django 3.0.2 on 2020-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200121_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
