# Generated by Django 3.0.2 on 2020-09-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0007_client_client_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('unread', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Object ID', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Any content model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
