# Generated by Django 3.0.2 on 2020-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notificationmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationmessages',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
