# Generated by Django 3.0.2 on 2020-09-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notificationmessages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmessages',
            name='tilte',
        ),
    ]
