# Generated by Django 3.0.2 on 2020-02-14 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_class', models.CharField(choices=[('ASSETS', 'ASSETS'), ('LIABILITIES', 'LIABILITIES'), ('INCOME', 'INCOME'), ('EXPENDITURE', 'EXPENDITURE')], max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrialBalanceLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_entry_type', models.CharField(choices=[('CR', 'CR'), ('DR', 'DR')], max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('related_trial_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction_trial_balance', to='products.ProductSubscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250)),
                ('transaction_description', models.CharField(blank=True, max_length=250, null=True)),
                ('transaction_category', models.IntegerField()),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_clearer', to=settings.AUTH_USER_MODEL)),
                ('transaction_completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_completer', to=settings.AUTH_USER_MODEL)),
                ('transaction_related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction_product', to='products.ProductSubscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_entry_type', models.CharField(choices=[('CR', 'CR'), ('DR', 'DR')], max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('related_ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction_product_ledger', to='ledgers.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='EndOfPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('period_ended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_ended_by', to=settings.AUTH_USER_MODEL)),
                ('period_started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_started_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(max_length=250)),
                ('account_name', models.CharField(max_length=250)),
                ('chart_level', models.IntegerField()),
                ('is_final_level', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('related_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_category', to='ledgers.CategoryClass')),
            ],
        ),
        migrations.CreateModel(
            name='ChartLevelLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_entry_type', models.CharField(choices=[('CR', 'CR'), ('DR', 'DR')], max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('related_chart_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction_product_chart_ledger', to='ledgers.Transaction')),
            ],
        ),
    ]
