# Generated by Django 3.0.2 on 2020-02-18 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalanceledger',
            name='related_trial_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_transaction_trial_balance', to='ledgers.Transaction'),
        ),
    ]
