# Generated by Django 3.0.2 on 2020-01-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200121_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.IntegerField()),
                ('date_cleared', models.DateTimeField(blank=True, null=True)),
                ('date_declined', models.DateTimeField(blank=True, null=True)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('loan_cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_deposit_receiver', to=settings.AUTH_USER_MODEL)),
                ('loan_received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laons_deposit_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('product_description', models.CharField(max_length=250)),
                ('product_category', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=25)),
                ('subscription_status', models.BooleanField(default=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user_subscriber', to=settings.AUTH_USER_MODEL)),
                ('related_client_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_client_subscription', to='accounts.Client')),
                ('related_product_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('account_status', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('related_savings_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_savings_product_subscription', to='products.ProductSubscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsWithdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_withdrawn', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('withdraw_method', models.IntegerField()),
                ('withdraw_comment', models.TextField(blank=True, null=True)),
                ('date_withdrawn', models.DateTimeField(auto_now_add=True)),
                ('related_savings_account_withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_savings_account_withdraw', to='products.Savings')),
                ('withdrawal_authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_withdrawal_authorizer', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_withdrawal_clearer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingsDeposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_deposited', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deposit_method', models.IntegerField()),
                ('date_deposited', models.DateTimeField(auto_now_add=True)),
                ('deposit_cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_deposit_clearer', to=settings.AUTH_USER_MODEL)),
                ('deposit_received_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_deposit_receiver', to=settings.AUTH_USER_MODEL)),
                ('related_savings_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_savings_account_deposit', to='products.Savings')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeesLevied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_category', models.IntegerField()),
                ('percentage_levied', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('fee_levied', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('frequency_levied', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('fees_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_fee_adder', to=settings.AUTH_USER_MODEL)),
                ('related_product_fees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_fees', to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='LoansRepaymentsFeesLevied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_levied', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_levied', models.DateTimeField(auto_now_add=True)),
                ('related_repayment_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_repayment_fees_levied', to='products.ProductFeesLevied')),
            ],
        ),
        migrations.CreateModel(
            name='LoansRepayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('payment_method', models.IntegerField()),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('related_loan_repayment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_repayments', to='products.Loans')),
            ],
        ),
        migrations.CreateModel(
            name='LoansGuarantors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_guarantor', to='accounts.Client')),
                ('related_loan_guaranted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_guarantors', to='products.Loans')),
            ],
        ),
        migrations.CreateModel(
            name='LoansDisbursements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('disbursement_method', models.IntegerField()),
                ('loan_status', models.IntegerField()),
                ('disbursed_on', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_extended', models.DateTimeField(blank=True, null=True)),
                ('date_written_off', models.DateTimeField(blank=True, null=True)),
                ('disbursed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_disburser', to=settings.AUTH_USER_MODEL)),
                ('disbursement_cleared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_disbursement_clearer', to=settings.AUTH_USER_MODEL)),
                ('related_loan_disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_disbursements', to='products.Loans')),
            ],
        ),
        migrations.CreateModel(
            name='LoansDisbursementFeesLevied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_levied', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('date_levied', models.DateTimeField(auto_now_add=True)),
                ('disbursement_related_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product_fees_levied', to='products.ProductFeesLevied')),
                ('disbursement_related_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_disbursement_fees', to='products.LoansDisbursements')),
            ],
        ),
        migrations.AddField(
            model_name='loans',
            name='related_loan_subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_product_subscription', to='products.ProductSubscriptions'),
        ),
    ]
