# Generated by Django 3.0.2 on 2020-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200218_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='payment_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='payment_period',
            field=models.CharField(choices=[('WEEKS', 'WEEKS'), ('MONTHS', 'MONTHS'), ('YEARS', 'YEARS')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
