# Generated by Django 3.0.2 on 2020-06-30 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type_name', models.CharField(max_length=250)),
                ('loan_type_description', models.TextField()),
                ('loan_type_code', models.CharField(max_length=250)),
                ('loan_type_added_on', models.DateTimeField(auto_now_add=True)),
                ('loan_type_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_type_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanTypeFeesApplicable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_loan_fee_category', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_type_fee_creator', to=settings.AUTH_USER_MODEL)),
                ('related_loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_fee', to='products.LoanType')),
            ],
        ),
        migrations.AddField(
            model_name='loans',
            name='related_loan_type_loans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_loan_type_loans', to='products.LoanType'),
            preserve_default=False,
        ),
    ]
