# Generated by Django 3.0.2 on 2020-06-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200630_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='related_product',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='loan_type_related_product', to='products.Product'),
            preserve_default=False,
        ),
    ]
