# Generated by Django 3.0.2 on 2020-07-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_loantype_related_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantypefeesapplicable',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
