# Generated by Django 3.0.2 on 2020-07-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_loantypefeesapplicable_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
