# Generated by Django 3.0.2 on 2020-07-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200720_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loansdisbursements',
            name='loan_status',
            field=models.IntegerField(default=0),
        ),
    ]
