# Generated by Django 3.2 on 2025-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200720_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loans',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loansdisbursementfeeslevied',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loansdisbursements',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loansguarantors',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loansrepayments',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loansrepaymentsfeeslevied',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loantype',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='loantypefeesapplicable',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='loans',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loansdisbursementfeeslevied',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loansdisbursements',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loansguarantors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loansrepayments',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loansrepaymentsfeeslevied',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loantype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loantypefeesapplicable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productfeeslevied',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productsubscriptions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savingsdeposits',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savingswithdrawal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
